class bfx_STR_DATA: ...
class bfx_Environment: ...
class bfx_Structure:
    def __init__(self, __src: bytes) -> None: ...
    def build(self, _str: bfx_STR_DATA) -> bytes: ...
    def run(self, _env: bfx_Environment, _str: bfx_STR_DATA) -> None: ...
class bfx_iostream:
    def __init__(self) -> None: ...
    def read(self, buffer_size=1024) -> bytes: ...
    def write(self, data: bytes) -> int: ...
class bfx_Program:
    def __init__(self, main_struct: bfx_Structure, _stream: bfx_iostream = None, _on_read = lambda: None, _on_write = lambda: None) -> None: ...
    def run(self) -> None: ...
    def build(self) -> None: ...