class bf_STR_DATA: ...
class bf_Environment: ...
class bf_Structure:
    def __init__(self, __src: bytes) -> None: ...
    def build(self, _str: bf_STR_DATA) -> bytes: ...
    def run(self, _env: bf_Environment, _str: bf_STR_DATA) -> None: ...
class bf_iostream:
    def __init__(self) -> None: ...
    def read(self, buffer_size=1024) -> bytes: ...
    def write(self, data: bytes) -> int: ...
class bf_Program:
    def __init__(self, main_struct: bf_Structure, _stream: bf_iostream = None, _on_read = lambda: None, _on_write = lambda: None) -> None: ...
    def run(self) -> None: ...
    def build(self) -> None: ...